### ISSUE TITLE
UDD 1.3.0 Validation - Cannot see new 1.3.0 entity files in listing for validation/ file upload

### ISSUE THREAD

**Issue by robwynj** [jiscdev/udd-web-validator#39]
The following are missing (UDD 1.3.0, vs 1.2.7):

https://github.com/jiscdev/analytics-udd/blob/v1.3.0/udd/period.md
https://github.com/jiscdev/analytics-udd/blob/v1.3.0/udd/student_id_map.md

**Comment by huwrobertsjisc** [comment]
The component extractor does pick up "period.md". The front end just does not show it.

The component extractor has no hope of picking up student_id_map because it is not listed as an entity in the "Core sections" or "Additional sections" found here:
https://github.com/jiscdev/analytics-udd/tree/v1.3.0

The web validator will be modified to look out for these 2 entities, however, the underlying UDD on GitHub needs to be changed.

**Comment by huwrobertsjisc** [comment]
These entities are now catered for in the Web Validator following this evening's UAT release.
