### ISSUE TITLE
Entity Record Counts - Not Correct in some instances

### ISSUE THREAD

**Issue by robwynj** [jiscdev/udd-web-validator#62]
Discrepancy in record counts / frequency - displayed different to what data (counts) are in the individual entity files (only see by one HEI so far - so treated as intermittent).

**Comment by huwrobertsjisc** [comment]
Currently waiting for files to be supplied before we can progress on this one.

**Comment by huwrobertsjisc** [comment]
Blocked as cannot get at the data files supplied by the institution.

**Comment by huwrobertsjisc** [comment]
Received data from institution. Data supplied by institution was in the form of an array of key value pairs instead of an array of record objects. It appeared in the Validator like there were far more records than there ought to be. The Validator is correct. Data is going to be corrected by the institution and resupplied.
